services:
  relay:
    build:
      context: ./relay
    image: moq-keycast-relay:local

    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./relay/qlogs:/qlogs
    command:
    - --server-bind
    - 0.0.0.0:4443
    - --tls-cert
    - /etc/letsencrypt/live/spaceinvasion.ddns.net/fullchain.pem
    - --tls-key
    - /etc/letsencrypt/live/spaceinvasion.ddns.net/privkey.pem
    - --web-https-listen
    - 0.0.0.0:4443
    - --web-https-cert
    - /etc/letsencrypt/live/spaceinvasion.ddns.net/fullchain.pem
    - --web-https-key
    - /etc/letsencrypt/live/spaceinvasion.ddns.net/privkey.pem
    - --auth-public
    - "moq-keycast"
    - --server-quic-qlog
    - /qlogs
    ports:
    - 4443:4443/tcp
    - 4443:4443/udp
    
  frontend:
    image: node:22
    working_dir: /app
    volumes:
    - ./TS/frontend:/app
    - /etc/letsencrypt:/etc/letsencrypt:ro
    command: sh -c "npm install && node node_modules/vite/bin/vite.js"
    ports:
    - 443:443
    depends_on:
    - relay
