listening-port=443
no-tcp
min-port=49152
max-port=49452
lt-cred-mech
realm=space-invasion.local
user=spaceinvasion:SaraeFranci1816
no-loopback-peers
no-multicast-peers
fingerprint
no-cli
no-tlsv1
no-tlsv1_1
log-file=stdout
